# Site settings
title: Lucas Matheus Gonçalves
email: lucas.66matheus@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page is a portfolio of my activities and jobs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "lucasmgon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lucas_mgon
github_username:  lucasmgon

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed